[tool.poetry]
name = "cloudflight-coding-contest"
version = "0.1.0"
description = ""
authors = ["Los Devaluados"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
